import {useState} from 'react';
import Page from '../components/Page';
import {useResource} from '../hooks/useResource';
import {getMenu,saveProduct,saveCategory} from '../services/menu';
import {money} from '../services/format';
const empty={name:'',description:'',price:'',category_id:'',available:true};
export default function Menu(){
 const r=useResource(getMenu,false),[form,setForm]=useState(null),[cat,setCat]=useState(null),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[availability,setAvailability]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(e,type){e.preventDefault();setBusy(true);setError('');try{if(type==='category'){await saveCategory(r.restaurant.id,cat);setCat(null);}else{await saveProduct(r.restaurant.id,form);setForm(null);}await r.refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const products=(r.data?.products||[]).filter(p=>String(p.name||'').toLowerCase().includes(search.toLowerCase())&&(category==='all'||p.category_id===category)&&(availability==='all'||p.available===(availability==='available')));
 return <Page title="Menú" description="Catálogo, categorías, precios y disponibilidad." resource={r} actions={<><button className="secondary" disabled={busy||r.loading||!!r.error} onClick={()=>{setCat({name:'',active:true});setForm(null);}}>Nueva categoría</button><button className="primary" disabled={busy||r.loading||!!r.error} onClick={()=>{setForm({...empty});setCat(null);}}>Nuevo producto</button></>}>
 {error&&<p className="notice error" role="alert">{error}</p>}
 {cat&&<form className="panel space-y-3" onSubmit={e=>save(e,'category')}><h2 className="font-semibold">{cat.id?'Editar categoría':'Nueva categoría'}</h2><label>Nombre de categoría<input required maxLength={100} value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/></label><label className="flex gap-2 items-center"><input type="checkbox" checked={cat.active} onChange={e=>setCat({...cat,active:e.target.checked})}/>Categoría activa</label><button className="primary" disabled={busy}>Guardar categoría</button><button type="button" className="secondary ml-2" disabled={busy} onClick={()=>setCat(null)}>Cancelar</button></form>}
 {form&&<form onSubmit={save} className="panel grid sm:grid-cols-2 gap-4"><h2 className="font-semibold sm:col-span-2">{form.id?'Editar producto':'Nuevo producto'}</h2><label>Nombre<input required maxLength={150} value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Precio (COP)<input required type="number" min="0" step="1" value={form.price} onChange={e=>update('price',e.target.value)}/></label><label>Categoría<select value={form.category_id||''} onChange={e=>update('category_id',e.target.value)}><option value="">Sin categoría</option>{r.data?.categories.map(c=><option value={c.id} key={c.id}>{c.name}{!c.active?' (inactiva)':''}</option>)}</select></label><label className="flex gap-2 items-center"><input type="checkbox" checked={form.available} onChange={e=>update('available',e.target.checked)}/>Disponible</label><label className="sm:col-span-2">Descripción<textarea maxLength={2000} value={form.description||''} onChange={e=>update('description',e.target.value)}/></label><div><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button><button type="button" className="secondary ml-2" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button></div></form>}
 <div className="grid sm:grid-cols-3 gap-3"><input aria-label="Buscar producto" placeholder="Buscar producto" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar categoría" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas las categorías</option>{r.data?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Filtrar disponibilidad" value={availability} onChange={e=>setAvailability(e.target.value)}><option value="all">Toda disponibilidad</option><option value="available">Disponibles</option><option value="unavailable">Agotados</option></select></div>
 <div className="flex flex-wrap gap-2">{r.data?.categories.map(c=><button className="badge" disabled={busy} key={c.id} onClick={()=>{setCat(c);setForm(null);}} title="Editar categoría">{c.name}{!c.active?' · Inactiva':''}</button>)}</div>
 <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{products.map(p=><article className="panel" key={p.id}><span className="badge">{p.available?'Disponible':'Agotado'}</span><p className="text-xs text-slate-500 mt-3">{r.data.categories.find(c=>c.id===p.category_id)?.name||'Sin categoría'}</p><h2 className="text-lg font-semibold mt-1">{p.name}</h2><p className="text-slate-500 text-sm mt-1">{p.description}</p><p className="font-semibold mt-3">{money(p.price)}</p><button className="secondary mt-4" disabled={busy} onClick={()=>{setForm(p);setCat(null);setError('');}}>Editar producto</button></article>)}</div>
 {!products.length&&<p className="panel">{r.data?.products.length?'No hay productos para estos filtros.':'Agrega el primer producto de tu restaurante.'}</p>}</Page>;
}
